/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.entity;  
@SuppressWarnings("all")
/** a pair of strings */
@org.apache.avro.specific.AvroGenerated
public class HalfOfStringPair extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HalfOfStringPair\",\"namespace\":\"ch04.entity\",\"doc\":\"a pair of strings\",\"fields\":[{\"name\":\"right\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence right;

  /**
   * Default constructor.
   */
  public HalfOfStringPair() {}

  /**
   * All-args constructor.
   */
  public HalfOfStringPair(java.lang.CharSequence right) {
    this.right = right;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return right;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: right = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'right' field.
   */
  public java.lang.CharSequence getRight() {
    return right;
  }

  /**
   * Sets the value of the 'right' field.
   * @param value the value to set.
   */
  public void setRight(java.lang.CharSequence value) {
    this.right = value;
  }

  /** Creates a new HalfOfStringPair RecordBuilder */
  public static avro.entity.HalfOfStringPair.Builder newBuilder() {
    return new avro.entity.HalfOfStringPair.Builder();
  }
  
  /** Creates a new HalfOfStringPair RecordBuilder by copying an existing Builder */
  public static avro.entity.HalfOfStringPair.Builder newBuilder(avro.entity.HalfOfStringPair.Builder other) {
    return new avro.entity.HalfOfStringPair.Builder(other);
  }
  
  /** Creates a new HalfOfStringPair RecordBuilder by copying an existing HalfOfStringPair instance */
  public static avro.entity.HalfOfStringPair.Builder newBuilder(avro.entity.HalfOfStringPair other) {
    return new avro.entity.HalfOfStringPair.Builder(other);
  }
  
  /**
   * RecordBuilder for HalfOfStringPair instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HalfOfStringPair>
    implements org.apache.avro.data.RecordBuilder<HalfOfStringPair> {

    private java.lang.CharSequence right;

    /** Creates a new Builder */
    private Builder() {
      super(avro.entity.HalfOfStringPair.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avro.entity.HalfOfStringPair.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing HalfOfStringPair instance */
    private Builder(avro.entity.HalfOfStringPair other) {
            super(avro.entity.HalfOfStringPair.SCHEMA$);
      if (isValidValue(fields()[0], other.right)) {
        this.right = data().deepCopy(fields()[0].schema(), other.right);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'right' field */
    public java.lang.CharSequence getRight() {
      return right;
    }
    
    /** Sets the value of the 'right' field */
    public avro.entity.HalfOfStringPair.Builder setRight(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.right = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'right' field has been set */
    public boolean hasRight() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'right' field */
    public avro.entity.HalfOfStringPair.Builder clearRight() {
      right = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public HalfOfStringPair build() {
      try {
        HalfOfStringPair record = new HalfOfStringPair();
        record.right = fieldSetFlags()[0] ? this.right : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
